### ISSUE TITLE
Refacting CSS

### ISSUE THREAD

**Issue by rohankumar-1** [ktpbu/ktpdatabase#15]
There is a lot of boilerplate CSS being done inline (i.e. `<h2 className="text-start">`). This could be refactored into a single CSS file that is imported to every .jsx file, that holds formatting info that all pages use (headers, paragraphs, etc). This is already a thing for page-content.css (to general page sizing), but can be extended further.

**Comment by victorverma3** [comment]
Potentially look into also using Tailwind CSS.

**Comment by victorverma3** [comment]
I migrated all vanilla css to tailwind css
